version: "3.7"

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: leopard
      POSTGRES_DB: questions_bd


volumes:
  postgres_data:
